Areas/Admin/Controllers/ComplexController.cs
using BotanicalDB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BotanicalDB.Areas.Admin.Controllers
{
    /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */

    // Routing added to direct to Admin area
    [Area("Admin")]
    public class ComplexController : Controller
    {
        private FowlerPlantContext plantContext { get; set; }

        public ComplexController(FowlerPlantContext plantContext)
        {
            this.plantContext = plantContext;
        }

        // Routing added to direct to Admin area
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Add()
        {
            return View(new SpeciesComplex());
        }

        // Routing added to direct to Admin area
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpPost]
        public IActionResult Add(SpeciesComplex complex)
        {
            // Validation of modelstate
            if (ModelState.IsValid)
            {
                plantContext.SpeciesComplexes.Add(complex);
                plantContext.SaveChanges();
                // Set message to be set to TempData
                TempData["message"] = $"{complex.ComplexName} was added to the database.";
                return RedirectToAction("Complex", "Home");
            }
            return View(complex);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            SpeciesComplex complex = plantContext.SpeciesComplexes.Find(id);
            return View(complex);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpPost]
        public IActionResult Edit(SpeciesComplex complex)
        {
            // Validation of modelstate
            if (ModelState.IsValid)
            {
                plantContext.SpeciesComplexes.Update(complex);
                plantContext.SaveChanges();
                // Set message to be set to TempData
                TempData["message"] = $"{complex.ComplexName} was edited in the database.";
                return RedirectToAction("Complex", "Home");
            }
            return View(complex);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            SpeciesComplex complex = plantContext.SpeciesComplexes.Find(id);
            plantContext.SpeciesComplexes.Remove(complex);
            plantContext.SaveChanges();
            // Set message to be set to TempData
            TempData["message"] = $"{complex.ComplexName} was deleted from the database.";
            return RedirectToAction("Complex", "Home");
        }
    }
}

Areas/Admin/Controllers/HomeController.cs
using BotanicalDB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BotanicalDB.Areas.Admin.Controllers
{
    /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */

    // Routing added to direct to Admin area
    [Area("Admin")]
    public class HomeController : Controller
    {
        private FowlerPlantContext plantContext { get; set; }

        public HomeController(FowlerPlantContext plantContext)
        {
            this.plantContext = plantContext;
        }

        // Action to access and display plant table
        // authorize admin user to access admin controls
        // Routing added to direct to Admin area
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        public IActionResult Index()
        {
            List<Plant> plantList = plantContext.Plants.Include(p => p.Complex).ToList();
            return View(plantList);
        }

        // Action to access and display speciescomplex table
        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        public IActionResult Complex()
        {
            List<SpeciesComplex> complexList = plantContext.SpeciesComplexes.ToList();
            return View(complexList);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        public IActionResult Privacy()
        {
            return View();
        }

        // Routing added to direct to Admin area
        [Route("[area]/[controller]/[action]")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Admin/Controllers/PlantController.cs
using BotanicalDB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BotanicalDB.Areas.Admin.Controllers
{
    /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */

    // Routing added to direct to Admin area
    [Area("Admin")]
    public class PlantController : Controller
    {
        private FowlerPlantContext plantContext { get; set; }

        public PlantController(FowlerPlantContext plantContext)
        {
            this.plantContext = plantContext;
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Add()
        {
            // Viewbag variable for SpeciesComplex list
            ViewBag.Complexes = plantContext.SpeciesComplexes.ToList();
            return View(new Plant());
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpPost]
        public IActionResult Add(Plant plant)
        {
            // Validation of modelstate
            if (ModelState.IsValid)
            {
                plantContext.Plants.Add(plant);
                plantContext.SaveChanges();
                // Set message to be set to TempData
                TempData["message"] = $"{plant.PlantName} was added to the database.";
                return RedirectToAction("Index", "Home");
            }
            // Viewbag variable for SpeciesComplex list
            ViewBag.Complexes = plantContext.SpeciesComplexes.ToList();
            return View(plant);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Plant plant = plantContext.Plants.Find(id);
            // Viewbag variable for SpeciesComplex list
            ViewBag.Complexes = plantContext.SpeciesComplexes.ToList();
            return View(plant);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpPost]
        public IActionResult Edit(Plant plant)
        {
            // Validation of modelstate
            if (ModelState.IsValid)
            {
                plantContext.Plants.Update(plant);
                plantContext.SaveChanges();
                // Set message to be set to TempData
                TempData["message"] = $"{plant.PlantName} was edited in the database.";
                return RedirectToAction("Index", "Home");
            }
            // Viewbag variable for SpeciesComplex list
            ViewBag.Complexes = plantContext.SpeciesComplexes.ToList();
            return View(plant);
        }

        // Routing added to direct to Admin area
        // authorize admin user to access admin controls
        [Authorize(Roles = "Admin")]
        [Route("[area]/[controller]/[action]")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Plant plant = plantContext.Plants.Find(id);
            plantContext.Plants.Remove(plant);
            plantContext.SaveChanges();
            // Set message to be set to TempData
            TempData["message"] = $"{plant.PlantName} was deleted from the database.";
            return RedirectToAction("Index", "Home");
        }
    }
}

Areas/Help/Controllers/HomeController.cs
using BotanicalDB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BotanicalDB.Areas.Help.Controllers
{
    /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */

    // Routing added to direct to Help area
    [Area("Help")]
    public class HomeController : Controller
    {
        // Routing added to direct to Help page 1
        [Route("[area]/[controller]/[action]")]
        public IActionResult Index()
        {
            return View();
        }

        // Routing added to direct to Help page 2
        [Route("[area]/[controller]/[action]")]
        public IActionResult PageTwo()
        {
            return View();
        }

        // Routing added to direct to Help page 3
        [Route("[area]/[controller]/[action]")]
        public IActionResult PageThree()
        {
            return View();
        }

        // Routing added to direct to Help area
        [Route("[area]/[controller]/[action]")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using BotanicalDB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BotanicalDB.Controllers
{
    /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */

    /* Cookies and session data being used to store favorite plant data
     * which is accessed through the Favorites navlink and displays the
     * number of favorites on the default area Index page
     */

    public class HomeController : Controller
    {
        private FowlerPlantContext plantContext {  get; set; }

        public HomeController(FowlerPlantContext plantContext)
        {
            this.plantContext = plantContext;
        }


        // Action to access and display plant table
        // Allow anonymous user to access index
        [AllowAnonymous]
        public IActionResult Index()
        {
            // Manage cookies and session data on start
            var session = new PlantSession(HttpContext.Session);
            List<Plant> myPlants = session.GetPlants();

            if (myPlants.Count == 0)
            {
                var cookies = new PlantCookies(Request.Cookies);
                string[] ids = cookies.GetMyPlantIds();

                if (ids.Length > 0)
                {
                    var myplants = plantContext.Plants
                        .Where(p => ids.Contains(p.PlantId.ToString()))
                        .ToList();
                    session.SetPlants(myplants);
                }
            }

            // Build index plant list
            List<Plant> plantList = plantContext.Plants.Include(p => p.Complex).ToList();
            return View(plantList);
        }

        // allow authorized user to access favorites
        [Authorize]
        [Route("[controller]/[action]")]
        public IActionResult Favorites()
        {
            List<Plant> plantList = plantContext.Plants.Include(p => p.Complex).ToList();
            return View(plantList);
        }

        // Routing added to direct to Default area
        // allow authorized user to access favorites
        [Authorize]
        [Route("[controller]/[action]/{id}")]
        // Action to add favorite plant to favorites list through session
        public IActionResult Favorite(int id)
        {
            PlantSession plantSession = new PlantSession(HttpContext.Session);
            PlantCookies plantCookies = new PlantCookies(Response.Cookies);

            List<Plant> plants = plantSession.GetPlants();
            Plant plant = plantContext.Plants.Find(id);
            if (plant != null)
            {
                if (plants.Where(p => p.PlantId == plant.PlantId).Select(p => p.PlantId).FirstOrDefault() == plant.PlantId)
                {
                    plants.Remove(plants.Where(p => p.PlantId == plant.PlantId).FirstOrDefault());
                }
                else
                {
                    plants.Add(plant);
                }
                plantSession.SetPlants(plants);
                plantCookies.SetMyPlantIds(plants);
            }
            return RedirectToAction("Index");
        }

        // allow authorized user to access complex list
        // Routing added to direct to Default area
        [Authorize]
        [Route("[controller]/[action]")]
        // Action to access and display speciescomplex table
        public IActionResult Complex()
        {
            List<SpeciesComplex> complexList = plantContext.SpeciesComplexes.ToList();
            return View(complexList);
        }

        // Routing added to direct to Default area
        [Route("[controller]/[action]")]
        public IActionResult Privacy()
        {
            return View();
        }

        // Routing added to direct to Default area
        [Route("[controller]/[action]")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Admin/Views/Home/Complex.cshtml
@{
     /*
     * Brett Fowler
     * Course CPT-231-424 - C# Programming II
     * Module 12 Assignnent
     * 2023 Fall
     */
}

@model List<SpeciesComplex>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Species Complex Table</h1>
</div>

@* If a successful add/edit/delete message has been passed to TempData, a message displays *@
@if (TempData.Keys.Contains("message"))
{
    <h4 class="bg-success text-center text-white p-2">@TempData["message"]</h4>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Complex ID</th>
            <th scope="col">Complex Name</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (SpeciesComplex complex in Model)
        {
            <tr>
                <td>
                    @complex.ComplexId
                </td>
                <td>
                    @complex.ComplexName
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm" asp-controller="Complex" asp-action="Edit" asp-route-id="@complex.ComplexId">Edit</a>
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm" asp-controller="Complex" asp-action="Delete" asp-route-id="@complex.ComplexId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-outline-secondary" asp-controller="Complex" asp-action="Add">Add</a>

Areas/Admin/Views/Home/Index.cshtml
@{
    /*
    * Brett Fowler
    * Course CPT-231-424 - C# Programming II
    * Module 12 Assignnent
    * 2023 Fall
    */
}

@model List<Plant>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Botanical Database</h1>
</div>


@* If a successful add/edit/delete message has been passed to TempData, a message displays *@
@if (TempData.Keys.Contains("message"))
{
    <h4 class="bg-success text-center text-white p-2">@TempData["message"]</h4>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Plant ID</th>
            <th scope="col">Plant Name</th>
            <th scope="col">Type</th>
            <th scope="col">Synonyms</th>
            <th scope="col">Distribution</th>
            <th scope="col">Species Complex</th>
            <th scope="col">Aquired Date</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Plant plant in Model)
        {
            <tr>
                <td>
                    @plant.PlantId
                </td>
                <td>
                    @plant.PlantName
                </td>
                <td>
                    @plant.PlantType
                </td>
                <td>
                    @plant.Synonym
                </td>
                <td>
                    @plant.Distribution
                </td>
                <td>
                    @plant.Complex.ComplexName
                </td>
                <td>
                    @plant.AquiredDate
                </td>
                <td>
                    @plant.PlantStatus
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm" asp-controller="Plant" asp-action="Edit" asp-route-id="@plant.PlantId">Edit</a>
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm" asp-controller="Plant" asp-action="Delete" asp-route-id="@plant.PlantId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-outline-secondary" asp-controller="Plant" asp-action="Add">Add</a>